CREATE USER 'deployerm'@'%' IDENTIFIED BY '6-zN4_Le9T3+Y&gy';
GRANT ALL PRIVILEGES ON *.* TO 'deployerm'@'%' WITH GRANT OPTION;

CREATE USER 'taras'@'%' IDENTIFIED BY 'd#79jgH+vU2M7@U!';
GRANT ALL PRIVILEGES ON *.* TO 'taras'@'%' WITH GRANT OPTION;

CREATE USER 'vova'@'%' IDENTIFIED BY '_E7y_FmR6y6~#nF8';
GRANT ALL PRIVILEGES ON *.* TO 'vova'@'%' WITH GRANT OPTION;

CREATE USER 'den'@'%' IDENTIFIED BY 's5Y&A9F9)x;ie4%T';
GRANT ALL PRIVILEGES ON *.* TO 'den'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;