apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-deployment
  namespace: x1
  labels:
    app: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring-container
        image: 233410784749.dkr.ecr.us-east-1.amazonaws.com/monitoring_x1:latest
        ports:
        - containerPort: 8081
        env:
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key