apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: x1
  labels:
    app: monitoring
spec:
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer