name: Recovery X1 services
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  recovery_services_x1:
    uses: Luna-Media-Group/actions/.github/workflows/recovery_aws_x1.yml@main
    with:
      runner_label: x1
      repo: ${{ github.repository }}

  recovery_front_x1:
    uses: Luna-Media-Group/actions/.github/workflows/deploy_recovery_front_aws.yml@main
    with:
      runner_label: x1
      repo: ${{ github.repository }}

  recovery_mysql_x1:
    uses: Luna-Media-Group/actions/.github/workflows/recovery_mysql.yml@main
    with:
      runner_label: x1
      repo: ${{ github.repository }}