apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: x1
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer